# Generated by Django 3.0.4 on 2020-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0004_auto_20200403_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='categories.Category'),
        ),
    ]
