# Generated by Django 3.0.4 on 2020-04-06 14:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_categories'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productitem',
            managers=[
                ('instock', django.db.models.manager.Manager()),
            ],
        ),
    ]
