# Generated by Django 3.0.4 on 2020-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200406_1415'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('RED', 'Red'), ('BROWN', 'Brown'), ('PURPLE', 'Purple')], db_index=True, default='Purple', max_length=255),
        ),
    ]
