# Generated by Django 3.0.4 on 2020-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200408_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('RED', 'Red'), ('BROWN', 'Brown'), ('PURPLE', 'Purple')], db_index=True, default=('PURPLE', 'Purple'), max_length=255),
        ),
    ]
